---
- name: Disable OS default site config
  command: 
    a2dissite 000-default
  sudo: 
    yes
  register: 
    result
  changed_when: 
    "'already disabled' not in result.stdout"
  notify:
      - restart-apache2
  tags:
      - apache2