---
- include:
    update-cache.yml
  when: 
    apache2_is_update_cache == true

- name: Install Apache2
  apt: 
    name=apache2
    state=installed
  sudo: 
    yes

- include:
    disable-default-site.yml
  when:
    apache2_is_disable_default_site == true